composer:
    build: config/docker/php/composer
    volumes:
        - composer.json:/scripts/composer.json:rw
        - composer.lock:/scripts/composer.lock:rw
        - bin:/scripts/bin:rw
    volumes_from:
        - vendor
vendor:
    build: config/docker/php/vendor
    volumes:
        - /scripts/vendor
behat:
    build: config/docker/php/behat
    volumes:
        - behat.yml:/scripts/behat.yml/:ro
        - src:/scripts/src/:ro
        - features:/scripts/features/:rw
    volumes_from:
        - vendor
    links:
        - redis28
        - redis30

redis28:
    image: redis:2.8

redis30:
    image: redis:3.0
